version: "3.6"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    ports:
      - "2345:5432"
    volumes:
      - mytopalbums:/var/lib/postgresql/data

  server:
    build: ./server/
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - "./server:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    # volumes:
    #   - .:/workspace:cached
    #   command: /bin/sh -c "while sleep 1000; do :; done"
    #   links:
    #     - client

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src/app/"
      - "/usr/src/app/node_modules"
    stdin_open: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  mytopalbums:
