version: "3.6"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    ports:
      - "2345:5432"
    volumes:
      - mytopalbums:/var/lib/postgresql/data

  server:
    build:
      context: ./services/server/
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    volumes:
      - "./services/server:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database

  client:
    build:
      context: ./services/client/
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - "./services/client:/usr/src/app/"
      - "/usr/src/app/node_modules"
    stdin_open: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

volumes:
  mytopalbums:
