version: "3.6"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    ports:
      - 2345:5432
    volumes:
      - mytopalbums:/var/lib/postgresql/data

  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile-dev
    volumes:
      - "./services/node:/usr/src/app"
      - "/usr/src/app/node_modules"
    #    ports:
    #      - 3001:3001
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres

  client:
    build:
      context: ./services/client/
      dockerfile: Dockerfile-dev
    volumes:
      - "./services/client:/usr/src/app/"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      # - REACT_APP_SIGNAL=${DOCKER_VAR}
    stdin_open: true
    depends_on:
      - node

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    depends_on:
      - node
      - client
    restart: always

volumes:
  mytopalbums:
